package com.andgatech.AHTech.util;

/**
 * Language/i18n utility.
 * Lang files are auto-generated from //#tr comments via addon.gradle preprocessing.
 */
public class LanguageManager {

    public static void init() {
        // Add any custom language registration logic here.
        // Most translation keys are auto-generated by the preprocessLangInJavaFiles task.
    }
}
