// 赛格大厦 (SEG Plaza) 精细版多方块机器
// 基于3张照片的建筑分析自动生成
// 总尺寸: 13W x 220H x 13D

package com.andgatech.AHTech.common.machine;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.*;
import static gregtech.api.enums.HatchElement.*;
import static gregtech.api.util.GTStructureUtility.*;

import com.gtnewhorizon.structurelib.structure.IStructureDefinition;
import com.gtnewhorizon.structurelib.structure.StructureDefinition;
import gregtech.api.enums.Textures;
import gregtech.api.interfaces.metatileentity.IGregTechTileEntity;
import gregtech.api.metatileentity.implementations.MTETieredMachine;
import gregtech.api.recipe.RecipeMap;
import gregtech.api.util.HatchElementBuilder;
import net.minecraft.item.ItemStack;

public class TST_SegPlaza extends GTCM_MultiMachineBase<TST_SegPlaza> {

    private static final String STRUCTURE_PIECE_MAIN = "main";
    private static final int horizontalOff = 6;
    private static final int verticalOff = 1;
    private static final int depthOff = 0;

    // -- Constructors --
    public TST_SegPlaza(int aID, String aName, String aNameRegional) {
        super(aID, aName, aNameRegional);
    }

    public TST_SegPlaza(String aName) { super(aName); }

    @Override
    public IMetaTileEntity newMetaEntity() { return new TST_SegPlaza(mName); }

    // -- Structure Definition --
    private static IStructureDefinition<TST_SegPlaza> STRUCTURE_DEF = null;

    @Override
    public IStructureDefinition<TST_SegPlaza> getStructureDefinition() {
        if (STRUCTURE_DEF == null) {
            STRUCTURE_DEF = StructureDefinition.<TST_SegPlaza>builder()
                .addShape(STRUCTURE_PIECE_MAIN, transpose(new String[][]{
        // Y=0 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=1 (13x13)
        {
            "PPPPHD~DHPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=2 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=3 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=4 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=5 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=6 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=7 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=8 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=9 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=10 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=11 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=12 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=13 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=14 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=15 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=16 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=17 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=18 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=19 (13x13)
        {
            "PPPPPPPPPPPPP",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "P-----------P",
            "PPPPPPPPPPPPP",
        },
        // Y=20 (13x13)
        {
            "SSSSSSSSSSSSS",
            "SSSSSSSSSSSSS",
            "SSTTTTTTTTTSS",
            "SST-------TSS",
            "SST-------TSS",
            "SST-------TSS",
            "SST-------TSS",
            "SST-------TSS",
            "SST-------TSS",
            "SST-------TSS",
            "SSTTTTTTTTTSS",
            "SSSSSSSSSSSSS",
            "SSSSSSSSSSSSS",
        },
        // Y=21 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=22 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=23 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=24 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=25 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=26 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=27 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=28 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=29 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=30 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=31 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=32 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=33 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=34 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=35 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=36 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=37 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=38 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=39 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=40 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=41 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=42 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=43 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=44 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=45 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=46 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=47 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=48 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=49 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=50 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=51 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=52 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=53 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=54 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=55 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=56 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=57 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=58 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=59 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=60 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=61 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=62 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=63 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=64 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=65 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=66 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=67 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=68 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=69 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=70 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=71 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=72 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=73 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=74 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=75 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=76 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=77 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=78 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=79 (9x9)
        {
            "             ",
            "             ",
            "  VVVVVVVVV  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  V-------V  ",
            "  VVVVVVVVV  ",
            "             ",
            "             ",
        },
        // Y=80 (9x9)
        {
            "             ",
            "             ",
            "  SSSSSSSSS  ",
            "  STTTTTTTS  ",
            "  ST-----TS  ",
            "  ST-----TS  ",
            "  ST-----TS  ",
            "  ST-----TS  ",
            "  ST-----TS  ",
            "  STTTTTTTS  ",
            "  SSSSSSSSS  ",
            "             ",
            "             ",
        },
        // Y=81 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=82 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=83 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=84 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=85 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=86 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=87 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=88 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=89 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=90 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=91 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=92 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=93 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=94 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=95 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=96 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=97 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=98 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=99 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=100 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=101 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=102 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=103 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=104 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=105 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=106 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=107 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=108 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=109 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=110 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=111 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=112 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=113 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=114 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=115 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=116 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=117 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=118 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=119 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=120 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=121 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=122 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=123 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=124 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=125 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=126 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=127 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=128 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=129 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=130 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=131 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=132 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   VVVVVVV   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   V-----V   ",
            "   VVVVVVV   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=133 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   SSSSSSS   ",
            "   STTTTTS   ",
            "   ST---TS   ",
            "   ST---TS   ",
            "   ST---TS   ",
            "   STTTTTS   ",
            "   SSSSSSS   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=134 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=135 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=136 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=137 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=138 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=139 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=140 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=141 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=142 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=143 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=144 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=145 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=146 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=147 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=148 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=149 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=150 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=151 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=152 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=153 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=154 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=155 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=156 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=157 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=158 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=159 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=160 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=161 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=162 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=163 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=164 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=165 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=166 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=167 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=168 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=169 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=170 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=171 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=172 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=173 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=174 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=175 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=176 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=177 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=178 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=179 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=180 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=181 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    VVVVV    ",
            "    V---V    ",
            "    V---V    ",
            "    V---V    ",
            "    VVVVV    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=182 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   KKKKKKK   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   KKKKKKK   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=183 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   KKKKKKK   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   KKKKKKK   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=184 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   KKKKKKK   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   KKKKKKK   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=185 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    KKKKK    ",
            "    K---K    ",
            "    K---K    ",
            "    K---K    ",
            "    KKKKK    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=186 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    KKKKK    ",
            "    K---K    ",
            "    K---K    ",
            "    K---K    ",
            "    KKKKK    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=187 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   KKKKKKK   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   KKKKKKK   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=188 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   KKKKKKK   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   KKKKKKK   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=189 (7x7)
        {
            "             ",
            "             ",
            "             ",
            "   KKKKKKK   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   K-----K   ",
            "   KKKKKKK   ",
            "             ",
            "             ",
            "             ",
        },
        // Y=190 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    KKKKK    ",
            "    K---K    ",
            "    K---K    ",
            "    K---K    ",
            "    KKKKK    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=191 (5x5)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "    KKKKK    ",
            "    K---K    ",
            "    K---K    ",
            "    K---K    ",
            "    KKKKK    ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=192 (3x3)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "     KKK     ",
            "     K-K     ",
            "     KKK     ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=193 (3x3)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "     KKK     ",
            "     K-K     ",
            "     KKK     ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=194 (3x3)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "     KKK     ",
            "     K-K     ",
            "     KKK     ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=195 (3x3)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "     KKK     ",
            "     K-K     ",
            "     KKK     ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=196 (3x3)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "     AAA     ",
            "     AAA     ",
            "     AAA     ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=197 (3x3)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "     AAA     ",
            "     AAA     ",
            "     AAA     ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=198 (3x3)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "     AAA     ",
            "     AAA     ",
            "     AAA     ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=199 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=200 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=201 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=202 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=203 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=204 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=205 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=206 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=207 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=208 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=209 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=210 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=211 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=212 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=213 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=214 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=215 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=216 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=217 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=218 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
        // Y=219 (1x1)
        {
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "      A      ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
            "             ",
        },
                }))
                // 裙楼方块
                .addElement('P', ofBlock(GregTechAPI.sBlockCasings1, 0))
                // 裙楼大门 (与裙楼方块相同，仅标记区分)
                .addElement('D', ofBlock(GregTechAPI.sBlockCasings1, 0))
                // 塔楼方块
                .addElement('T', ofBlock(GregTechAPI.sBlockCasings2, 15))
                // 竖向装饰线条 (可用不同方块以突出效果)
                .addElement('V', ofBlock(GregTechAPI.sBlockCasings4, 1))
                // 退台过渡层
                .addElement('S', ofBlock(GregTechAPI.sBlockCasings3, 2))
                // 皇冠方块
                .addElement('K', ofBlock(GregTechAPI.sBlockCasings4, 8))
                // 天线方块
                .addElement('A', ofBlock(GregTechAPI.sBlockCasings5, 4))
                // Hatch 位置
                .addElement('H',
                    HatchElementBuilder.<TST_SegPlaza>builder()
                        .atLeast(InputBus, OutputBus, InputHatch, OutputHatch,
                                 Energy.or(ExoticEnergy), Maintenance)
                        .adder(TST_SegPlaza::addToMachineList)
                        .dot(1)
                        .casingIndex(16)
                        .buildAndChain(GregTechAPI.sBlockCasings1, 0))
                .build();
        }
        return STRUCTURE_DEF;
    }

    // -- Three Required Methods --
    @Override
    public boolean checkMachine(IGregTechTileEntity aBaseMetaTileEntity, ItemStack aStack) {
        repairMachine();
        return checkPiece(STRUCTURE_PIECE_MAIN, horizontalOff, verticalOff, depthOff);
    }

    @Override
    public void construct(ItemStack stackSize, boolean hintsOnly) {
        buildPiece(STRUCTURE_PIECE_MAIN, stackSize, hintsOnly, horizontalOff, verticalOff, depthOff);
    }

    @Override
    public int survivalConstruct(ItemStack stackSize, int elementBudget,
            ISurvivalBuildEnvironment env) {
        if (this.mMachine) return -1;
        return survivalBuildPiece(STRUCTURE_PIECE_MAIN, stackSize,
            horizontalOff, verticalOff, depthOff, elementBudget, env, false, true);
    }

    // -- Recipe Map --
    @Override
    public RecipeMap<?> getRecipeMap() {
        return null; // TODO: 指定配方表
    }
}
